export const typeError ={
    UNIDENTIFIED:"UNIDENTIFIED",
    DATABASE:"DATABASE",
    PRISMA_CONNECTION:"PRISMA CONNECTION ERROR",
    PRISMA_VALIDATION:"PRISMA INVALID FIELDS",
    PRISMA_DATABASE:"PRISMA DATABASE INVALID ACTION",
    JAVASCRIPT_ERROR:"JAVASCRIPT RUNTIME ERROR",
    EMPTY_BODY: "EMPTY_BODY",
    BAD_INPUT_DATA: "BAD_INPUT_DATA"
}